### ISSUE TITLE
ModuleNotFoundError: No module named 'arrow'

### ISSUE THREAD

**Issue by liuchangjun** [csuldw/AntSpider#4]
starbook:scrapy star$ pwd
/Users/star/project/docker/AntSpider/scrapy

starbook:scrapy star$ scrapy list
Traceback (most recent call last):
  File "/Users/star/Library/Python/3.7/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/Users/star/Library/Python/3.7/lib/python/site-packages/scrapy/cmdline.py", line 144, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/Users/star/Library/Python/3.7/lib/python/site-packages/scrapy/crawler.py", line 265, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/Users/star/Library/Python/3.7/lib/python/site-packages/scrapy/crawler.py", line 137, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/Users/star/Library/Python/3.7/lib/python/site-packages/scrapy/crawler.py", line 345, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/Users/star/Library/Python/3.7/lib/python/site-packages/scrapy/spiderloader.py", line 60, in from_settings
    return cls(settings)
  File "/Users/star/Library/Python/3.7/lib/python/site-packages/scrapy/spiderloader.py", line 24, in __init__
    self._load_all_spiders()
  File "/Users/star/Library/Python/3.7/lib/python/site-packages/scrapy/spiderloader.py", line 46, in _load_all_spiders
    for module in walk_modules(name):
  File "/Users/star/Library/Python/3.7/lib/python/site-packages/scrapy/utils/misc.py", line 77, in walk_modules
    submod = import_module(fullpath)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/star/project/docker/AntSpider/scrapy/douban/spiders/movie_meta.py", line 13, in <module>
    import douban.validator as validator
  File "/Users/star/project/docker/AntSpider/scrapy/douban/validator.py", line 10, in <module>
    import arrow
ModuleNotFoundError: No module named 'arrow'

**Comment by KiteFlyKid** [comment]
Hi, I got the same problem.
Have you fixed it?

**Comment by ElderWanng** [comment]
> pip install arrow
